//
// Generated file, do not edit! Created by nedtool 5.4 from dsResponse.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __DSRESPONSE_M_H
#define __DSRESPONSE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>dsResponse.msg:16</tt> by nedtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * message DsResponse
 * {
 *     int source;
 *     int destination;
 *     int degre;
 *     int degreSat;
 *     bool colored;
 *     int hopCount = 0;
 * }
 * </pre>
 */
class DsResponse : public ::omnetpp::cMessage
{
  protected:
    int source;
    int destination;
    int degre;
    int degreSat;
    bool colored;
    int hopCount;

  private:
    void copy(const DsResponse& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DsResponse&);

  public:
    DsResponse(const char *name=nullptr, short kind=0);
    DsResponse(const DsResponse& other);
    virtual ~DsResponse();
    DsResponse& operator=(const DsResponse& other);
    virtual DsResponse *dup() const override {return new DsResponse(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual int getDestination() const;
    virtual void setDestination(int destination);
    virtual int getDegre() const;
    virtual void setDegre(int degre);
    virtual int getDegreSat() const;
    virtual void setDegreSat(int degreSat);
    virtual bool getColored() const;
    virtual void setColored(bool colored);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DsResponse& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DsResponse& obj) {obj.parsimUnpack(b);}


#endif // ifndef __DSRESPONSE_M_H

