//
// Generated file, do not edit! Created by nedtool 5.4 from dsRequest.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __DSREQUEST_M_H
#define __DSREQUEST_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>dsRequest.msg:17</tt> by nedtool.
 * <pre>
 * message DsRequest
 * {
 *     int source;
 *     int destination;
 *     int degre;
 *     int color;
 *     int hopCount = 0;
 * }
 * </pre>
 */
class DsRequest : public ::omnetpp::cMessage
{
  protected:
    int source;
    int destination;
    int degre;
    int color;
    int hopCount;

  private:
    void copy(const DsRequest& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DsRequest&);

  public:
    DsRequest(const char *name=nullptr, short kind=0);
    DsRequest(const DsRequest& other);
    virtual ~DsRequest();
    DsRequest& operator=(const DsRequest& other);
    virtual DsRequest *dup() const override {return new DsRequest(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual int getDestination() const;
    virtual void setDestination(int destination);
    virtual int getDegre() const;
    virtual void setDegre(int degre);
    virtual int getColor() const;
    virtual void setColor(int color);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DsRequest& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DsRequest& obj) {obj.parsimUnpack(b);}


#endif // ifndef __DSREQUEST_M_H

